version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "hennesk"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "hennesk"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
